#!/bin/bash

source "./config"

iptables -F $CHAIN_NAME

while IFS=',' read -r port user; do
    iptables -D INPUT -p tcp --dport $port -j REJECT 2>/dev/null
done < "$USER_FILE"

echo "Shadowsocks usage reset at $(date)" >> "$LOG_FILE"
