#!/bin/bash

usage() {
    echo "Usage: $0 <start|stop|restart|status|enable|disable|logs> <port>"
    exit 1
}

if [[ $# -ne 2 ]]; then
    usage
fi

PORT="$2"
SERVICE="ss-user@$PORT"

case "$1" in
    start|stop|restart|status|is-active|enable|disable)
        systemctl $1 "$SERVICE"
        ;;
    logs)
        journalctl -u "$SERVICE" -e
        ;;
    *)
        usage
        ;;
esac
