#!/bin/bash

# Root check
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

mkdir -p /etc/ssmgr
cp -r ./* /etc/ssmgr

chmod +x /etc/ssmgr/user
chmod +x /etc/ssmgr/quota
chmod +x /etc/ssmgr/service
chmod +x /etc/ssmgr/ssmgr.py

ln -s /etc/ssmgr/ssmgr.py /usr/local/bin/ssmgr
ln -s /etc/ssmgr/ss-user@.service /etc/systemd/system/ss-user@.service

echo "0 3 * * * root ssmgr check-expired" > /etc/cron.d/check-expired
chmod 644 "/etc/cron.d/check-expired"

# apt-get update && apt-get install -y shadowsocks-libev simple-obfs iptables
