#!/bin/bash

source ./config

cp ./ss-user@.service /etc/systemd/system/ss-user@.service
cp ./ssctl /usr/local/bin/ssctl
cp ./sslimit /usr/local/bin/sslimit
cp ./ssmgr /usr/local/bin/ssmgr

chmod +x /usr/local/bin/ssctl
chmod +x /usr/local/bin/sslimit
chmod +x /usr/local/bin/ssmgr
chmod +x ./ssctl
chmod +x ./sslimit
chmod +x ./ssmgr

apt-get update && apt-get install -y shadowsocks-libev simple-obfs iptables
